# Generated by Django 4.2.29 on 2026-03-22 00:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(blank=True, max_length=255, null=True)),
                ('reponse_correcte', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('explication', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Question Quiz',
                'verbose_name_plural': 'Questions Quiz',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatriculation', models.CharField(max_length=20, unique=True)),
                ('marque', models.CharField(max_length=50)),
                ('modele', models.CharField(max_length=50, verbose_name='Modèle')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Véhicule',
                'verbose_name_plural': 'Véhicules',
                'ordering': ['marque', 'modele'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('eleve', 'Élève'), ('moniteur', 'Moniteur'), ('admin', 'Administrateur')], default='eleve', max_length=10)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('adresse', models.TextField(blank=True, null=True)),
                ('numero_permis', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numéro de permis')),
                ('date_inscription', models.DateTimeField(default=django.utils.timezone.now)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profils',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('methode', models.CharField(choices=[('carte', 'Carte bancaire'), ('especes', 'Espèces'), ('virement', 'Virement'), ('cheque', 'Chèque')], default='carte', max_length=15, verbose_name='Méthode de paiement')),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('en_attente', 'En attente'), ('rembourse', 'Remboursé')], default='en_attente', max_length=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('eleve', models.ForeignKey(limit_choices_to={'profile__role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure', models.DateTimeField(verbose_name='Date et heure')),
                ('duree', models.IntegerField(default=60, help_text='Durée de la leçon en minutes', verbose_name='Durée (minutes)')),
                ('statut', models.CharField(choices=[('disponible', 'Disponible'), ('complete', 'Complète'), ('effectuee', 'Effectuée'), ('annulee', 'Annulée')], default='disponible', max_length=15)),
                ('notes', models.TextField(blank=True, null=True, verbose_name="Notes d'évaluation")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('moniteur', models.ForeignKey(limit_choices_to={'profile__role': 'moniteur'}, on_delete=django.db.models.deletion.CASCADE, related_name='lessons_moniteur', to=settings.AUTH_USER_MODEL)),
                ('vehicule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecole.vehicle')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['date_heure'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reservation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('en_attente', 'En attente'), ('annulee', 'Annulée')], default='confirmee', max_length=15)),
                ('eleve', models.ForeignKey(limit_choices_to={'profile__role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='ecole.lesson')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-date_reservation'],
                'unique_together': {('eleve', 'lecon')},
            },
        ),
    ]
