# Generated by Django 4.2.29 on 2026-03-23 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecole', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('fichier_pdf', models.FileField(blank=True, null=True, upload_to='cours_pdfs/', verbose_name='Fichier PDF optionnel')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage du cours")),
            ],
            options={
                'verbose_name': 'Cours de Code',
                'verbose_name_plural': 'Cours de Code',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='code_obtenu',
            field=models.BooleanField(default=False, verbose_name='Code obtenu'),
        ),
        migrations.AddField(
            model_name='profile',
            name='docs_validates',
            field=models.BooleanField(default=False, verbose_name='Documents validés'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neph_status',
            field=models.CharField(choices=[('na', 'Non demandé'), ('attente', 'En attente'), ('valide', 'Validé')], default='na', max_length=20, verbose_name='Statut NEPH'),
        ),
        migrations.AddField(
            model_name='profile',
            name='passport_scan',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Passeport'),
        ),
        migrations.AddField(
            model_name='profile',
            name='visa_proof',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='Preuve de Visa'),
        ),
    ]
